server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 2MB
      enabled: true
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/

app:
  upload-dir: ./uploads